title: SONJASPER
author:
  name: CHENGJIE XU
  email: xcj@outlook.com
description: > # this means to ignore newlines until "show_excerpts:"
  Developer | DevOps | Gamer

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

  # generate social links in footer
  social_links:
    # twitter:
    # github:
    # devto:
    # dribbble:
    # facebook:
    # flickr:
    # instagram:
    # linkedin:
    # pinterest:
    # youtube:
    # youtube_channel:
    # youtube_channel_name:
    # telegram:
    # googleplus:
    # microdotblog:
    # keybase:

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#   - about.md

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

google_analytics: UA-63706050-1

disqus:
  shortname: sonjasper

paginate: 50
paginate_path: "/page/:num"